<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Rewards</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>e5a3559b-76e8-4d27-8d1f-5fe64b33c365</testSuiteGuid>
   <testCaseLink>
      <guid>9ecb89ac-d3f3-45c6-85ff-14104e2576cd</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Rewards/Rewards</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>23e7b592-c63e-40ce-846a-35122c3eb475</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Rewards/DB_Rewards</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>04a51732-c75c-4487-9cd8-b274a3a25715</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>136e8fd2-bd80-4908-9973-4c28f3d6fd22</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9dec3591-cdbe-4cdf-a70e-8f62eb497f94</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>eedf2178-08cc-4ee5-86c8-ed529805d8f3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b5ad28c8-842b-4e5f-ad1d-872054d3eefb</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
